### ISSUE TITLE
Port all tests from original repo

### ISSUE THREAD

**Issue by storming0x** [storming0x/foundry-yearnV2-gen-lev-lending#1]
https://github.com/fp-crypto/yearnV2-gen-lev-lending

**Comment by anticlimactic** [comment]
Other TODOs:

The following tests fail:

To reproduce: pin the block to 14000000 (or some other number of your choice)
```
testDeleverageToZero(uint256) 
testLargeDeleverageParameterChange(uint256)
testLargeManualDeleverageToZero(uint256)
testMigration(uint256)
testAprWithCooldown(uint256)
testHarvestAfterLongIdlePeriod(uint256)
testWithdraw(uint256,bool)
```

- Testing against WETH causes all tests to fail as the `LendingPool` throws an error.
